### ISSUE TITLE
Bug in fee-retrieval logic

### ISSUE THREAD

**Issue by engenegr** [fiatjaf/trustedcoin#5]
I have an intuition that it may be related to channel force-closes.

```
Oct 15 07:06:57 satoshis-box lightningd[30247]: plugin-trustedcoin returning block 652815, 0000000000000000000a22cf38…, 1415537 bytes
Oct 15 07:07:18 satoshis-box lightningd[30247]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 15 07:07:18 satoshis-box lightningd[30247]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x746303]
Oct 15 07:07:18 satoshis-box lightningd[30247]: goroutine 393 [running]:
Oct 15 07:07:18 satoshis-box lightningd[30247]: main.getFeeRatesFromEsplora(0xc000326738, 0x0, 0x0)
Oct 15 07:07:18 satoshis-box lightningd[30247]:         /home/fiatjaf/comp/go/src/github.com/fiatjaf/lightningd-gjson-rpc/cmd/trustedcoin/estimatefees.go:23 +0x113
Oct 15 07:07:18 satoshis-box lightningd[30247]: main.main.func3(0xc0000b60f0, 0x0, 0x815e78, 0x0, 0x0, 0x0, 0x0)
Oct 15 07:07:18 satoshis-box lightningd[30247]:         /home/fiatjaf/comp/go/src/github.com/fiatjaf/lightningd-gjson-rpc/cmd/trustedcoin/main.go:90 +0x34
Oct 15 07:07:18 satoshis-box lightningd[30247]: github.com/fiatjaf/lightningd-gjson-rpc/plugin.handleMessage(0xc0000b60f0, 0xc0000582d0, 0xc000484f87, 0x3, 0x784060, 0xc0004
Oct 15 07:07:18 satoshis-box lightningd[30247]:         /home/fiatjaf/comp/go/src/github.com/fiatjaf/lightningd-gjson-rpc/plugin/plugin.go:204 +0x5c2
Oct 15 07:07:18 satoshis-box lightningd[30247]: created by github.com/fiatjaf/lightningd-gjson-rpc/plugin.(*Plugin).Listener
Oct 15 07:07:18 satoshis-box lightningd[30247]:         /home/fiatjaf/comp/go/src/github.com/fiatjaf/lightningd-gjson-rpc/plugin/plugin.go:182 +0xa7e
Oct 15 07:07:20 satoshis-box lightningd[30247]: txprepare: Lost connection to the RPC socket.
Oct 15 07:07:20 satoshis-box lightningd[30247]: keysend: Lost connection to the RPC socket.
Oct 15 07:07:20 satoshis-box lightningd[30247]: autoclean: Lost connection to the RPC socket.
Oct 15 07:07:20 satoshis-box systemd[1]: lightningd.service: Main process exited, code=dumped, status=6/ABRT
Oct 15 07:07:20 satoshis-box systemd[1]: lightningd.service: Failed with result 'core-dump'.
```

**Comment by engenegr** [comment]
New occurrence
```
Oct 26 14:40:44 satoshis-box lightningd[13422]: plugin-trustedcoin getblock error: Get "https://mempool.emzy.de/api/block-height/654240": dial tcp 136.243.53.40:443: connect: connection refused
Oct 26 14:40:53 satoshis-box lightningd[13422]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 26 14:40:53 satoshis-box lightningd[13422]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7521b3]
Oct 26 14:40:53 satoshis-box lightningd[13422]: goroutine 74 [running]:
Oct 26 14:40:53 satoshis-box lightningd[13422]: main.getFeeRatesFromEsplora(0x576fa5, 0x0, 0x0)
Oct 26 14:40:53 satoshis-box lightningd[13422]:         /home/ilya/Code/Golang/trustedcoin/estimatefees.go:23 +0x133
Oct 26 14:40:53 satoshis-box lightningd[13422]: main.main.func3(0xc0000b00f0, 0x0, 0x80d8d0, 0x0, 0x0, 0x0, 0x0)
Oct 26 14:40:53 satoshis-box lightningd[13422]:         /home/ilya/Code/Golang/trustedcoin/main.go:101 +0x34
Oct 26 14:40:53 satoshis-box lightningd[13422]: github.com/fiatjaf/lightningd-gjson-rpc/plugin.handleMessage(0xc0000b00f0, 0xc000058050, 0xc0003365cc, 0x3, 0x78a480, 0xc000336608, 0xc000336610, 0xc, 0x7a0f80, 0xc0013ff2f0)
Oct 26 14:40:53 satoshis-box lightningd[13422]:         /home/ilya/Code/Golang/env/pkg/mod/github.com/fiatjaf/lightningd-gjson-rpc@v1.1.0/plugin/plugin.go:204 +0x5b9
Oct 26 14:40:53 satoshis-box lightningd[13422]: created by github.com/fiatjaf/lightningd-gjson-rpc/plugin.(*Plugin).Listener
Oct 26 14:40:53 satoshis-box lightningd[13422]:         /home/ilya/Code/Golang/env/pkg/mod/github.com/fiatjaf/lightningd-gjson-rpc@v1.1.0/plugin/plugin.go:182 +0xa9a
Oct 26 14:40:55 satoshis-box lightningd[13422]: keysend: Lost connection to the RPC socket.
Oct 26 14:40:55 satoshis-box lightningd[13422]: autoclean: Lost connection to the RPC socket.
Oct 26 14:40:55 satoshis-box systemd[1]: lightningd.service: Main process exited, code=dumped, status=6/ABRT
Oct 26 14:40:55 satoshis-box systemd[1]: lightningd.service: Failed with result 'core-dump'.
Oct 26 14:41:05 satoshis-box systemd[1]: lightningd.service: Service hold-off time over, scheduling restart.
Oct 26 14:41:05 satoshis-box systemd[1]: lightningd.service: Scheduled restart job, restart counter is at 12.
Oct 26 14:41:05 satoshis-box systemd[1]: Stopped C-Lightning daemon.
Oct 26 14:41:05 satoshis-box systemd[1]: Starting C-Lightning daemon..
```

Also another crash after getBlock

```
Oct 26 14:39:39 satoshis-box lightningd[13332]: plugin-trustedcoin getblock error: Get "https://mempool.emzy.de/api/block-height/654249": dial tcp 136.243.53.40:443: connect: connection refused
Oct 26 14:39:39 satoshis-box lightningd[13332]: lightningd: FATAL SIGNAL 11 (version v0.9.1)
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf37fdc send_backtrace
Oct 26 14:39:39 satoshis-box lightningd[13332]:         common/daemon.c:38
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf3806f crashdump
Oct 26 14:39:39 satoshis-box lightningd[13332]:         common/daemon.c:51
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x7f8af4172fcf ???
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ???:0
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf45aaf bitcoin_block_blkid
Oct 26 14:39:39 satoshis-box lightningd[13332]:         bitcoin/block.c:229
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcef7432 new_block
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/chaintopology.c:848
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcef7641 init_topo
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/chaintopology.c:935
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcef63ce getrawblockbyheight_callback
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/bitcoind.c:449
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf1f688 plugin_response_handle
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/plugin.c:367
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf1f79b plugin_read_json_one
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/plugin.c:473
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf1f90b plugin_read_json
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/plugin.c:517
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf68ddd next_plan
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ccan/ccan/io/io.c:59
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf692cc do_plan
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ccan/ccan/io/io.c:407
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf692f9 io_ready
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ccan/ccan/io/io.c:417
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf6abc5 io_loop
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ccan/ccan/io/poll.c:445
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf03ba2 io_loop_with_timers
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/io_loop_with_timers.c:24
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcef9671 setup_topology
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/chaintopology.c:1171
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcf0710c main
Oct 26 14:39:39 satoshis-box lightningd[13332]:         lightningd/lightningd.c:934
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x7f8af4155b96 ???
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ???:0
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0x5598dcef5b09 ???
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ???:0
Oct 26 14:39:39 satoshis-box lightningd[13332]: 0xffffffffffffffff ???
Oct 26 14:39:39 satoshis-box lightningd[13332]:         ???:0
Oct 26 14:39:40 satoshis-box lightningd[13332]: lightningd: Died with signal 11
```

**Comment by fiatjaf** [comment]
`nil` pointer on line 23, which is https://github.com/fiatjaf/trustedcoin/pull/6/files#diff-40f70d26607cccffc2d7fbb3a73acba692d7a571d397a339a97bb6741f34df03R23

**Comment by engenegr** [comment]
It seems that the bug has something to do with RAM shortage of the VPS instance. Because after enabling swap I don't see any bugs at all.
